gardener/gardener-extension-networking-cilium

.ci/pipeline_definitions

Update slack channel name. 
```improvement operator
Release now points to the right slack channel.
```

Update slack channel name

---

.ci/pipeline_definitions

Adds the verify step to all jobs, using the base definition.

Add verify step to all jobs

---

Dockerfile
go.mod
hack/update-codegen.sh
vendor/modules.txt

Update go version
```improvement operator
NONE
```

Update go version to 1.14

---

.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/flaking-test.md
hack/update-github-template.sh
vendor/github.com/gardener/gardener/.github/ISSUE_TEMPLATE/bug.md
vendor/github.com/gardener/gardener/.github/ISSUE_TEMPLATE/doc.go
vendor/github.com/gardener/gardener/.github/ISSUE_TEMPLATE/feature.md
vendor/github.com/gardener/gardener/.github/ISSUE_TEMPLATE/flaking-test.md
vendor/github.com/gardener/gardener/.github/ISSUE_TEMPLATE/support.md
vendor/github.com/gardener/gardener/.github/doc.go
vendor/github.com/gardener/gardener/.github/pull_request_template.md
vendor/modules.txt

Update PR template
```improvement operator
None
```

update pr template

---

charts/images.yaml

/priority normal
Update cilium to v1.9.5, which includes many [bugfixes](https://github.com/cilium/cilium/releases/tag/v1.9.5).
```improvement operator
Update cilium to v1.9.5, which includes many bugfixes.
```

Update cilium to v1.9.5

---

.ci/pipeline_definitions

Update golang image to golang:1.17.6.
Fixes #
```other operator
none
```

update golang image to golang:1.17.6

---

.ci/pipeline_definitions
Dockerfile

Update to latest golang patch.
None.
```other operator
```

Update to latest golang patch.

---

charts/images.yaml

Add CVE categorisation.
None.
```other operator
```

Add CVE categorisation.

---

charts/images.yaml
charts/internal/cilium/charts/agent/templates/clusterrole.yaml
charts/internal/cilium/charts/agent/templates/clusterrolebinding.yaml
charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/charts/agent/templates/role.yaml
charts/internal/cilium/charts/agent/templates/rolebinding.yaml
charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/charts/hubble-relay/templates/clusterrole.yaml
charts/internal/cilium/charts/hubble-relay/templates/clusterrolebinding.yaml
charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
charts/internal/cilium/charts/hubble-relay/templates/job.yaml
charts/internal/cilium/charts/hubble-relay/templates/service.yaml
charts/internal/cilium/charts/hubble-ui/templates/clusterrole.yaml
charts/internal/cilium/charts/hubble-ui/templates/clusterrolebinding.yaml
charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
charts/internal/cilium/charts/hubble-ui/templates/hubble-peer-svc.yaml
charts/internal/cilium/charts/hubble-ui/templates/svc.yaml
charts/internal/cilium/charts/operator/templates/clusterrole.yaml
charts/internal/cilium/charts/operator/templates/clusterrolebinding.yaml
charts/internal/cilium/charts/operator/templates/deployment.yaml
charts/internal/cilium/values.yaml

Update cilium to `v1.13.0`.
Fixes #
```other operator
Update cilium to `v1.13.0`.
```

Update cilium to v1.13.0

---

.ci/pipeline_definitions
Dockerfile
go.mod

Bump builder image from `golang:1.19.4` to `golang:1.20.2`
Fixes #
```other operator
Bump builder image from `golang:1.19.4` to `golang:1.20.2`
```

update to golang 1.20

---

charts/images.yaml
charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/charts/agent/templates/svc.yaml
charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
charts/internal/cilium/charts/hubble-relay/templates/job.yaml
charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
charts/internal/cilium/charts/operator/templates/deployment.yaml
charts/internal/cilium/values.yaml

Update cilium to `v1.13.1`.
Fixes #
```other operator
Update cilium to `v1.13.1`.
```

update to cilium v1.13.1

---

charts/internal/cilium/charts/agent/templates/podsecuritypolicy.yaml

/kind bug
Add hostport 4244 to psp.
Fixes #
```other operator
none
```

add hostport 4244 to psp

---

.ci/pipeline_definitions
Dockerfile

Update to golang 1.20.4.
None.
```other operator
Update golang to 1.20.4.
```

Update to golang 1.20.4

---

charts/images.yaml
charts/internal/cilium/charts/agent/templates/clusterrole.yaml
charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/charts/hubble-relay/templates/clusterrole.yaml
charts/internal/cilium/charts/hubble-relay/templates/configmap.yaml
charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
charts/internal/cilium/charts/hubble-relay/values.yaml
charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
charts/internal/cilium/charts/operator/templates/clusterrole.yaml
charts/internal/cilium/charts/operator/templates/deployment.yaml
charts/internal/cilium/charts/operator/templates/podsecuritypolicy.yaml
charts/internal/cilium/values.yaml
pkg/apis/cilium/types_network.go
pkg/apis/cilium/v1alpha1/types_network.go
pkg/charts/utils.go

Update cilium to `v1.14.0`. For more information see the [release notes](https://github.com/cilium/cilium/releases/tag/v1.14.0).
Fixes #
```other operator
Update cilium to `v1.14.0`.
```

Update cilium to v1.14.0

---

charts/images.yaml

Update to cilium `v1.14.1`.
Fixes #
```other operator
Update to cilium `v1.14.1`.
```

update to cilium v1.14.1

---

pkg/webhook/shoot/add.go

Add object selector and failure policy to node-local-dns webhook.
Before this change, the mutating webhook for node-local-dns got called for all configmaps and daemonsets in `kube-system` namespace. However, with https://github.com/gardener/gardener/pull/8505 it is possible to restrict it further so that the mutating webhook is only called for relevant entities.
This allows us to set the correct failure policy without having a big blast radius in case the webhook fails.
None.
Waiting until https://github.com/gardener/gardener/pull/8505 is merged and released.
```other operator
The …
```

Add object selector and failure policy to node-local-dns webhook

---

charts/internal/cilium/charts/config/templates/configmap.yaml

/kind bug
Egress gateway validation is fixed in case kube-proxy is disabled.
Fixes #
```other operator
Egress gateway validation is fixed in case kube-proxy is disabled.
```

fix egress gateway validation

---

imagevector/images.yaml

Update cilium to `v1.14.3`.
Fixes #
```other operator
Update cilium to `v1.14.3`.
```

update cilium to v1.14.3

---

docs/usage/usage.md

Update documentation for egress gateway feature.
Fixes #
```other operator
none
```

update cilium docs for egress gateway feature

---

charts/internal/cilium/charts/config/templates/configmap.yaml

Fail if egress gateway is enabled without using an overlay.
Fixes #
```other operator
none
```

fail if egress gateway is enabled without using an overlay

---

imagevector/images.yaml

Update cilium to `v1.14.4`.
Fixes #
```other operator
Update cilium to `v1.14.4`.
```

update cilium to v1.14.4

---

Makefile
charts/internal/cilium/charts/config/templates/configmap.yaml
imagevector/images.yaml

Update cilium to `v1.14.6`.
Fixes #
```other operator
Update cilium to `v1.14.6`
```

Update cilium to v1.14.6

---

charts/gardener-extension-admission-cilium/charts/runtime/templates/deplyoment.yaml

/kind bug
Set leader election namespace in cilium admission deployment.
Fixes #
```other operator
Set leader election namespace in cilium admission deployment.
```

set LEADER_ELECTION_NAMESPACE in deployment

---

.golangci.yaml

unpin go version for linters
Fixes #
```other operator
none
```

unpin go version for linters

---

imagevector/images.yaml

Add scanning hint for envoy so that the correct `v8` version is used for static container image analysis.
None.
```other operator
```

Add scanning hint for envoy

---

test/e2e/common_test.go

/kind bug
Fixes #
```other operator
```

Fix e2e tests.

---

charts/internal/cilium/charts/config/templates/configmap.yaml

Fixes #
```other operator
Set policy-cidr-match-mode to match node CIDRs in networkpolicies.
```

Set policy-cidr-match-mode: "node" to match node CIDRs in networkpolicies.

---

charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
imagevector/images.yaml

Update cilium to `v1.15.6`.  
Fixes #
```other operator
Update cilium to `v1.15.6`.
```

update cilium to v1.15.6

---

charts/internal/cilium/charts/agent/templates/clusterrole.yaml
charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/charts/envoy/Chart.yaml
charts/internal/cilium/charts/envoy/templates/configmap.yaml
charts/internal/cilium/charts/envoy/templates/daemonset.yaml
charts/internal/cilium/charts/envoy/templates/serviceaccount.yaml
charts/internal/cilium/charts/envoy/values.yaml
charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
charts/internal/cilium/charts/hubble-relay/templates/job.yaml
charts/internal/cilium/charts/hubble-relay/templates/role.yaml
charts/internal/cilium/charts/hubble-relay/templates/rolebinding.yaml
charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
charts/internal/cilium/charts/operator/templates/clusterrole.yaml
charts/internal/cilium/charts/operator/templates/deployment.yaml
charts/internal/cilium/values.yaml
imagevector/image_finders.go
imagevector/images.yaml
pkg/charts/utils.go
pkg/cilium/types.go

Update cilium to `v1.16.1` and enable cilium-envoy to enable features like (Ingress, Gateway API, Network Policies with L7 functionality, L7 Protocol Visibility).
Fixes #
```other operator
Update cilium to `v1.16.1` and enable cilium-envoy to enable features like (Ingress, Gateway API, Network Policies with L7 functionality, L7 Protocol Visibility).
```

update cilium to v1.16.1

---

charts/internal/cilium/charts/envoy/templates/daemonset.yaml
charts/internal/cilium/charts/envoy/templates/service.yaml
imagevector/images.yaml

Update to cilium `v1.16.2`.
Fixes #
```other operator
Update to cilium `v1.16.2`.
```

update to cilium v1.16.2

---

imagevector/images.yaml

Remove digest from cilium-envoy image.
Fixes #
```other operator
none
```

remove digest from cilium-envoy image

---

test/templates/network-connectivity-test.yaml.tpl

Update connectivity test image to `v.1.9.0`.
Fixes #
```other operator
none
```

update connectivity test image

---

test/templates/network-connectivity-test.yaml.tpl

Skip check-log-errors and client-egress-tls-sni test.
Fixes #
```other operator
none
```

skip check-log-errors and client-egress-tls-sni test

---

imagevector/images.yaml

Update scanning packages to correct version.
Fixes #
```other operator
none
```

update scanning packages to correct version

---

test/templates/network-connectivity-test.yaml.tpl

Update cilium cli image to version `1.10.0`.
Fixes #
```other operator
```

update cilium cli image to version 1.10.0

---

.github/workflows/build.yaml

/area compliance
/kind task
Fixes #
```other operator
Fix 'add-reports-to-component-descriptor' build step
```

Fix 'add-reports-to-component-descriptor' build step

---

pkg/charts/utils.go

/kind bug
Fix Dual-Stack handling of native IPv6 routing CIDR.
Previously the IPv6 pod range was expected to be the first in the list. However, this is not always the case. Therefore, use the first CIDR with the correct IP family instead.
Fixes #
```other operator
Dual-Stack should now work consistently regardless of the order of the IP families.
```

Fix Dual-Stack handling of native IPv6 routing CIDR.

---

renovate.json5

Run `make generate` for renovate update pull requests.
Fixes #
```other operator
```

Run `make generate` for renovate update pull requests.
