charts/images.yaml

Updates Cilium to v1.8.2
```improvement operator
Cilium is now running on v1.8.2. 
```

Update Cilium to v1.8.2

---

docs/usage-as-end-user.md

Add documentation for end user to cilium
```improvement operator
None
```

Add end user documentation to cilium

---

charts/images.yaml

Update Cilium to version [v1.8.4](https://github.com/cilium/cilium/releases/tag/v1.8.4)
```improvement operator
Cilium is now running on v1.8.4. 
```

Update Cilium to version v1.8.4

---

charts/images.yaml
charts/internal/cilium/charts/agent/templates/clusterrole.yaml
charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/charts/operator/templates/clusterrole.yaml
charts/internal/cilium/charts/operator/templates/deployment.yaml
charts/internal/cilium/values.yaml

Update cilium to `v1.8.5` and update missing clusterrole permissions.
```improvement operator
Update cilium to `v1.8.5` and update missing clusterrole permissions.
```

Update cilium to v1.8.5 and update missing clusterrole permissions.

---

Makefile
cmd/gardener-extension-networking-cilium/app/app.go

/kind bug
/area quality
Ref https://github.com/gardener/gardener-extension-networking-calico/pull/42
```improvement operator
An issue causing networking-cilium controller to not respect the `--max-concurrent-reconciles` flag is now fixed.
```

Honor --max-concurrent-reconciles flag

---

Makefile
cmd/gardener-extension-networking-cilium/app/app.go

/area cost
Ref gardener/gardener-extension-networking-calico#55
```improvement operator
The cache for Secrets and ConfigMaps is now disabled to decrease the extension controller's memory footprint
```

Disable cache for Secrets and ConfigMaps

---

.gitignore
charts/images.yaml
charts/internal/cilium/charts/agent/templates/clusterrole.yaml
charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/charts/hubble-relay/templates/clusterrole.yaml
charts/internal/cilium/charts/hubble-relay/templates/clusterrolebinding.yaml
charts/internal/cilium/charts/hubble-relay/templates/configmap.yaml
charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
charts/internal/cilium/charts/hubble-relay/templates/job.yaml
charts/internal/cilium/charts/hubble-relay/templates/serviceaccount.yaml
charts/internal/cilium/charts/hubble-relay/values.yaml
charts/internal/cilium/charts/hubble-ui/templates/clusterrole.yaml
charts/internal/cilium/charts/hubble-ui/templates/configmap.yaml
charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
charts/internal/cilium/charts/hubble-ui/templates/svc.yaml
charts/internal/cilium/charts/operator/templates/clusterrole.yaml
charts/internal/cilium/values.yaml
docs/usage-as-end-user.md
pkg/charts/config.go
pkg/charts/utils.go
pkg/charts/values.go
pkg/cilium/types.go
pkg/controller/actuator_reconcile.go
pkg/imagevector/image_finders.go

/priority normal
This PR updates Cilium to `v.1.9.4`. The ipam mode is switched from legacy `hostscope` mode which is removed to `cluter-pool` ipam mode.
Fixes #
```improvement operator
Cilium is updated to `v.1.9.4`. The ipam mode is switched from legacy `hostscope` mode which is removed to `cluter-pool` ipam mode.  
```

Update cilium to v.1.9.4 and switch ipam mode to cluster-pool

---

charts/images.yaml

Update cilium to v1.9.6.
See [cilium 1.9.6 release notes](https://github.com/cilium/cilium/releases/tag/v1.9.6).
```other operator
Update cilium to v1.9.6, which includes many bugfixes.
```

Update cilium to v1.9.6.

---

Makefile

The container image tag should be the same in ordinary local builds and the continuous integration pipeline.
This is analogous to the other gardener extensions.
/kind technical-debt
For unknown reasons, the default container image tag used in the standard build and the continuous integration pipeline differ. This change unifies them.
Fixes #
```other operator
```

Unify container image tag in Makefile

---

charts/images.yaml
charts/internal/cilium/charts/agent/templates/clusterrole.yaml
charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
charts/internal/cilium/charts/hubble-ui/templates/configmap.yaml
charts/internal/cilium/charts/operator/templates/clusterrole.yaml
charts/internal/cilium/charts/operator/templates/deployment.yaml
charts/internal/cilium/values.yaml

Update cilium to `v1.10.1`
```other operator
Update cilium to `v1.10.1`
```

Update cilium to v1.10.1

---

charts/images.yaml
charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/charts/agent/values.yaml
charts/internal/cilium/values.yaml
pkg/charts/utils.go
pkg/charts/values.go
pkg/cilium/types.go
pkg/controller/actuator_reconcile.go
pkg/imagevector/image_finders.go

Cilium documentation recommends to remove the iptables rules generated by kube-proxy before activating service routing in cilium.
Unfortunately, there is no easy way to execute a command on each node just once. Therefore, we simply use an init container of the daemon set.
Cilium documentation recommends to remove the iptables rules generated by kube-proxy before activating service routing in cilium.
Unfortunately, there is no easy way to execute a command on each node just once. Therefore, we simply use an init container of the daemon set.
None
```other operator
```

Added kube-proxy clean up as init container in case cilium performs the service routing

---

charts/images.yaml
charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/values.yaml

Update cilium to `v1.10.3` and use cgroupv2.
Fixes #
```other operator
Update cilium to `v1.10.3` and use cgroupv2.
```

update cilium to v1.10.3

---

go.mod
pkg/controller/actuator.go
pkg/controller/actuator_reconcile.go
vendor/modules.txt

/kind technical-debt
- It replaces github.com/pkg/errors with errors from the stdlib. It introduces appropriate changes where needed so the functionality to remain unchanged (this is achieved by Introducing custom Unwrap method)
- Replaces verb %v with %w to actually wrap the error where is needed
Fixes https://github.com/gardener/gardener-extension-networking-cilium/issues/60
```other operator
none
```

replace error pkg

---

charts/images.yaml

Update cilium to `v1.11.1` which contains several bugfixes for agent instability. For more information see the [release notes](https://github.com/cilium/cilium/releases/tag/v1.11.1).
Fixes #
```other operator
Update cilium to `v1.11.1` which contains several bugfixes for agent instability.
```

Update cilium to v1.11.1

---

charts/internal/cilium/charts/hubble-relay/templates/job.yaml

GRM is recreating the job after its ttl expires and gets cleaned up after a successful run.
Therefore  `ttlSecondsAfterFinished` was set to `86400` seconds to generate new certs for hubble once a day from currently every 30 minutes.
```other operator
none
```

generate once a day the new certs for hubble

---

charts/internal/cilium/charts/agent/templates/daemonset.yaml

/kind bug
Add init container to cilium agent which disables reverse path filtering (rp_filter).
Fixes #51
```other operator
Add init container to cilium agent which disables reverse path filtering (rp_filter).
```

Add init container to cilium agent which disables rp_filter

---

charts/internal/cilium/charts/network-policy/Chart.yaml
charts/internal/cilium/charts/network-policy/templates/dns.yaml

/kind bug
Added cilium network policy to allow non-pod entities on remote nodes to access the cluster dns server.
In case cilium's dns based policy rules are utilized the dns traffic is redirected through a proxy component
owned by cilium. However, this proxy component needs to be allowed to perform dns requests. The default
network policy does not seem to be sufficient. Therefore, we add this special policy in addition.
Fixes #35
```other operator
Added cilium network policy to allow cilium's dns proxy to perform dns requests to make dns based policy working.
```

Added cilium network policy to allow non-pod entities on remote nodes to access the cluster dns server.

---

charts/images.yaml
charts/internal/cilium/charts/agent/templates/clusterrole.yaml

Update cilium to `v1.11.3`. For more information see the [release notes](https://github.com/cilium/cilium/releases/tag/v1.11.3).
Fixes #
```other operator
Update cilium to `v1.11.3`.
```

Update cilium to v1.11.3

---

charts/internal/cilium/charts/agent/values.yaml

Add memory requests and limits to cilium agent container.
We want to limit the memory consumption of cilium agent in case of bugs.
The way we set the limits we also have to specify the requests. Otherwise,
the requests will be equal to the limits, which would be wasteful.
None.
```other operator
Added default memory resource requests/limits to cilium-agent.
```

Add memory requests and limits to cilium agent container.

---

charts/images.yaml
charts/internal/cilium/charts/agent/templates/clusterrole.yaml
charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/charts/hubble-relay/templates/configmap.yaml
charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
charts/internal/cilium/charts/hubble-ui/templates/hubble-peer-svc.yaml
charts/internal/cilium/charts/operator/templates/clusterrole.yaml
charts/internal/cilium/values.yaml

Update cilium to v1.11.5. For more information see the [release notes](https://github.com/cilium/cilium/releases/tag/v1.11.5).
Fixes #
```other operator
Update cilium to v1.11.5.
```

Update cilium to v1.11.5

---

pkg/charts/utils.go

/kind bug
Consider tunnel mode and debug option in the provider config during reconciliation.
The documentation stated that tunnel mode and debug option could be set in the
provider configuration. Unfortunately, the values were ignored in the past.
This change should fix that.
None.
```other operator
Tunnel mode and debug option are now properly handled when specified in the cilium provider configuration.
```

Consider tunnel mode and debug option in the provider config during reconciliation.

---

charts/internal/cilium/charts/operator/values.yaml

Add default memory requests/limits to etcd-operator container.
None.
```other operator
Add default memory requests/limits to etcd-operator container.
```

Add default memory requests/limits to etcd-operator container.

---

docs/usage-as-end-user.md

Extend documentation for `bpfSocketLBHostnsOnly` and `egressGateway` flag.
Fixes #
```other operator
none
```

Extend documentation for bpfSocketLBHostnsOnly and egressGateway flag

---

.golangci.yaml

/kind bug
Some of the linters don't work correctly with 1.18, ref https://github.com/golangci/golangci-lint/issues/2649
We are not using generics, so let's pin this to 1.17 until 1.18 is fully supported
Fixes #
```other operator
none
```

Exclude some linter checks which don't work with golang v1.18

---

charts/internal/cilium/values.yaml

/kind bug
Fix cannot merge map onto non-map for key 'egressGateway'.
Fixes #
```other operator
none
```

fix cannot merge map onto non-map for key 'egressGateway'

---

charts/internal/cilium/charts/config/templates/configmap.yaml

/kind bug
Fix wrong path in `configmap.yaml` template.
Fixes #
```other operator
none
```

fix wrong path in configmap.yaml template

---

Dockerfile

/area networking security open-source
This PR changes the base image for networking and admission services from alpine to [distroless](https://github.com/GoogleContainerTools/distroless). The processes will now use a non root user for their execution. This will reduce the attack surface of the images.
Fixes #
```other operator
The extension now uses `distroless` instead of `alpine` as a base image.
```

use distroless image for garnder networking cilium extension

---

charts/images.yaml
charts/internal/cilium/charts/agent/templates/clusterrole.yaml
charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/charts/hubble-relay/templates/clusterrole.yaml
charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
charts/internal/cilium/charts/hubble-relay/templates/job.yaml
charts/internal/cilium/charts/hubble-relay/templates/service.yaml
charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
charts/internal/cilium/charts/hubble-ui/templates/svc.yaml
charts/internal/cilium/charts/operator/templates/clusterrole.yaml
charts/internal/cilium/charts/operator/templates/deployment.yaml
charts/internal/cilium/values.yaml

Update cilium to `v1.12.0`. For more information see the [release notes](https://github.com/cilium/cilium/releases/tag/v1.12.0).
Fixes #
```other operator
Update cilium to `v1.12.0`.
```

Update cilium to v1.12.0

---

charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml

/kind bug
Fix hubble deployment.
Fixes #
```other operator
none
```

fix hubble deployment

---

charts/internal/cilium/charts/operator/templates/deployment.yaml
pkg/charts/utils.go

/kind bug
Ensure that the kubernetes api server host is always set when running without kube-proxy.
During creation of a cluster there are a few races ongoing. This is especially true if
cilium is running as kube-proxy replacement.
cilium-agent waits for the cilium CRDs to be present in the kubernetes api server, before
performing its ordinary operation, i.e. there is no service routing in case kube-proxy is
disabled and no CNI operations will succeed.
cilium-operator is responsible for adding the CRDs on startup. However, unless the kubernetes
service host is specified, it will fall back on the in cluster name of the kubernetes api
server, i.e. kubernetes.default.svc.cluster.local. Unfortunately, this …

Ensure that the kubernetes api server host is always set when running without kube-proxy.

---

charts/internal/cilium/charts/agent/templates/podsecuritypolicy.yaml

/kind bug
Fix pod security policy for cilium 1.12 so that it works even if allowPrivilegedContainers is set to false.
With cilium 1.12, almost all containers of cilium are no longer running as privileged containers,
but specify their required capabilities instead. (The only exception being our kube-proxy cleanup
container.) Unfortunately, the corresponding adaption of the pod security policy was forgotten.
This change updates the pod security policy accordingly so that cilium can run again with
allowPrivilegedContainers=false.
None.
```other operator
Networking provider cilium works again with …
```

Fix pod security policy for cilium 1.12 so that it works even if allowPrivilegedContainers is set to false.

---

pkg/webhook/shoot/node_local_dns.go

/kind bug
Fix mutating web hook for node-local-dns to work with non-default ports.
In case a non-default port, i.e. not port 8080, was used the specification
of the liveness probe and the exposed health check port may not fit after
the mutating web hook for node-local-dns has been applied. This should be
fixed now for the standard case.
(Port 8080 was not a good choice for a host port and therefore it was
changed.)
None.
With https://github.com/gardener/gardener/pull/6477 the default health check port was changed. Hence, the port needs to be kept by the mutating web hook.
```other operator
Cilium works again with …
```

Fix mutating web hook for node-local-dns to work with non-default ports.

---

charts/internal/cilium/charts/agent/templates/daemonset.yaml

/area security
According to my testing the `cilium-kube-proxy-clean-up` init container of `cilium` can run with the `NET_ADMIN` capability added and does not need to run in privileged mode.
Part of https://github.com/gardener-security/standard-compliance/issues/3
```other operator
The cilium/cilium-kube-proxy-clean-up init container no longer runs in privileged mode.
```

Do not run cilium/cilium-kube-proxy-clean-up in privileged mode

---

charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/charts/operator/templates/deployment.yaml
pkg/charts/utils.go

/area open-source
`PodSecurityPolicy` is deprecated and will be disabled in kubernetes v1.25+.
End-users are provided an option to migrate their PSPs before upgrading and disable the `PodSecurityPolicy` admission plugin in the ShootSpec. 
In that case, we should stop deploying our PSPs as well.
- This PR adapts the mutating fields of the existing PSPs in the PodSpec. 
- Stop deploying PSPs if the plugin is disabled in the Shoot.
Part of https://github.com/gardener/gardener/issues/5250
/squash
```breaking operator
Please make sure you're running gardener@v1.52 or above before upgrading to this …
```

Don't deploy `PSP`s when `PodSecurityPolicy` plugin is disabled 

---

charts/images.yaml
charts/internal/cilium/charts/agent/templates/daemonset.yaml

/kind technical-debt
Remove support for kubernetes < 1.17 for kube-proxy.
None.
Kubernetes < 1.17 has long run out of community support. There is no need to have support in this extension for it.
```other operator
Removed support for kubernetes < 1.17 from cilium networking provider.
```

Remove support for kubernetes < 1.17 for kube-proxy.

---

charts/images.yaml
charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/values.yaml
pkg/charts/utils.go
pkg/cilium/types.go
pkg/imagevector/image_finders.go

Improve kubernetes conformance per default by using portmap cni binary.
Kubernetes conformance tests fail if cilium's native host port/ip implementation
is used. Therefore, this change switches to using portmap cni binary per default.
None.
```other operator
Kubernetes conform hostPort/hostIP handling with cilium clusters.
```

Improve kubernetes conformance per default by using portmap cni binary.

---

charts/internal/cilium/charts/agent/templates/clusterrole.yaml

/kind cleanup
adds correct RBAC permissions for cilium-agent 
Fixes #125 
```other operator
```

add rbac permissions for nodes/status

---

.ci/pipeline_definitions
Dockerfile
go.mod
pkg/charts/charts_suite_test.go

Update go version to `v1.19.2`.  This fixes CVE-2022-27664.
Fixes #
```other operator
Update go version to `v1.19.2`. 
```

update go version to v1.19.2

---

charts/images.yaml
charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
charts/internal/cilium/charts/operator/templates/deployment.yaml
charts/internal/cilium/values.yaml
pkg/apis/cilium/types_network.go
pkg/apis/cilium/v1alpha1/types_network.go
pkg/charts/utils.go

Update cilium to `v1.12.3`.
Fixes #
```other operator
Update cilium to `v1.12.3`.
```

update cilium to v1.12.3

---

charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/values.yaml
pkg/charts/config.go
pkg/charts/utils.go
pkg/charts/values.go
pkg/controller/actuator_reconcile.go

IPAM mode is changed to `kubernetes` for new shoot cluster. `cluster-pool` mode is preserved for existing ones.
BPF masquerading is enabled.
Fixes #
```other operator
IPAM mode is changed to `kubernetes` for new shoot cluster. `cluster-pool` mode is preserved for existing ones.
BPF masquerading is enabled.
```

switch default ipam to kubernetes and use bpf masquerading

---

example/20-network.yaml

/area usability
Updates Gardener API Core version in examples and markdowns to `core.gardener.cloud/v1beta1`
Fixes #
```other operator
NONE
```

Update API Core version in examples to core.gardener.cloud/v1beta1

---

charts/images.yaml

Update cilium to `v1.12.4`.
Fixes #
```other operator
Update cilium to `v1.12.4`.
```

update cilium to v1.12.4

---

charts/images.yaml

Update portmap copier to v0.2.0.
None.
```other operator
Updated portmap-copier to v0.2.0
```

Update portmap copier to v0.2.0

---

charts/internal/cilium/charts/hubble-relay/templates/podsecuritypolicy.yaml

/kind bug
Add missing annotations for seccomp profiles to pod security policies.
The change introducing seccomp profiles (#129) did not add the annotations for the hubble-relay pod security policies. This results in clusters with allowPrivilegedContainers set to false to fail in case hubble is enabled. This change resolves this issue.
Fixes #90
```other operator
PodSecurityPolicy for hubble-relay is now correctly allowing seccomp profiles to be used
```

Add missing annotations for seccomp profiles to pod security policies.

---

charts/internal/cilium/charts/hubble-relay/templates/job.yaml

/kind bug
Use resources.gardener.cloud/delete-on-invalid-update annotation for hubble generate certificate job.
Changes in the generate certificate job caused issues as the spec.template of the job is immutable. The gardener resource manager allows to workaround this limitation when a resource is annotated with resources.gardener.cloud/delete-on-invalid-update=true. By setting this annotation, it is possible to properly use a container image overwrite or update the resource on upstream updates.
Fixes #49.
Renamed the job to the upstream equivalent.
```other operator
hubble-generate-certs job can now use image …
```

Use resources.gardener.cloud/delete-on-invalid-update annotation for hubble generate certificate job.

---

charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
charts/internal/cilium/charts/hubble-relay/templates/job.yaml
charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
charts/internal/cilium/charts/nodeinit/templates/daemonset.yaml
charts/internal/cilium/charts/operator/templates/deployment.yaml
example/20-network.yaml
hack/api-reference/cilium.json
hack/api-reference/config.json

/kind cleanup
Drop support for kubernetes < 1.20.
Part of https://github.com/gardener/gardener/issues/6911
```other operator
Cilium networking no longer supports Shoots with Кubernetes version < 1.20.
```

Drop support for kubernetes < 1.20 for cilium extension

---

pkg/controller/actuator_reconcile.go

This PR disables the native routing mode for cilium. The reason for that is that an issue with cilium was identified which breaks the native routing mode as cilium drops some cluster internal traffic due to the loss of identity. An upstream issue was opened under: https://github.com/cilium/cilium/issues/23376.
Fixes #
```other operator
Disable native routing mode for cilium.
```

disable native routing mode for cilium

---

charts/internal/cilium/charts/agent/templates/daemonset.yaml

/area robustness
This PR adds the `node.gardener.cloud/critical-component` label to `cilium` DaemonSet introduced in https://github.com/gardener/gardener/pull/7406 
Part of  https://github.com/gardener/gardener/issues/7117
https://github.com/gardener/gardener/pull/7406 is merged
```feature user
`cilium` is marked as a node-critical component. With this, workload pods are only scheduled to a `Node` if it runs a ready `cilium` pod.
```

Mark cilium as node-critical component

---

charts/internal/cilium-monitoring/cilium-agent-metrics-dashboard.json
charts/internal/cilium-monitoring/cilium-operator-metrics-dashboard.json
charts/internal/cilium-monitoring/hubble-metrics-dashboard.json
charts/internal/cilium/values.yaml

Dashboard for cilium agent, cilium operator and hubble is updated and deprecated http metric is replaced.
```other operator
Dashboard for cilium agent, cilium operator and hubble is updated and deprecated http metric is replaced.
```

update cilium dashboards and replace deprecated http metric

---

charts/internal/cilium/charts/operator/templates/deployment.yaml
charts/internal/cilium/values.yaml
pkg/charts/config.go
pkg/charts/utils.go

/area high-availability
/kind bug
Please see issue https://github.com/gardener/gardener-extension-networking-cilium/issues/165
Fixes https://github.com/gardener/gardener-extension-networking-cilium/issues/165
I don't know if this is the right way to do this.
I just thought I might try :)
```bugfix operator
The cilium operator now only runs with multiple replicas if the shoot cluster has multiple nodes
```

Enable operator ha mode only on cluster with nodes > 1

---

hack/test-e2e-provider-local.sh

/kind bug
add domain mapping for e2e-default shoot cluster to /etc/hosts file
Fixes #
```other operator
none
```

add domain mapping for e2e-default shoot cluster to /etc/hosts

---

charts/internal/cilium/charts/agent/templates/podsecuritypolicy.yaml

/kind bug
enable hostport 4244 independently of prometheus
```other operator
none
```

enable hostport 4244 independently of prometheus

---

charts/images.yaml
charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/values.yaml
pkg/charts/utils.go
pkg/cilium/types.go
pkg/imagevector/image_finders.go

Portmap copier was introduced in https://github.com/gardener/gardener-extension-networking-cilium/pull/128 to be conform with the k8s conformance tests.
As the conformance tests are failing with a `host port validation` error when running without kube-proxy, the portmap copier is of no benefit and can be removed.
Fixes #
```other operator
Portmap copier is removed.
```

remove portmap copier

---

hack/test-e2e-provider-local.sh

/kind test
Export artifacts analogous to gardener/gardener in end-to-end tests.
This should provide more data from the end-to-end cluster for error analysis.
None.
```other operator
```

Export artifacts analogous to gardener/gardener in end-to-end tests

---

charts/gardener-extension-admission-cilium/charts/runtime/templates/service.yaml
charts/gardener-extension-admission-cilium/values.yaml

/area high-availability
The following Service is adapted to be topology-aware:
- `gardener-extension-admission-cilium` - the Service is consumed by `gardener-apiserver` for the webhook communication
Part of https://github.com/gardener/gardener/issues/6718
N/A
```other operator
The `gardener-extension-admission-cilium` Service in the `gardener-extension-admission-cilium` chart can now be configured to be topology-aware.
```

Make the `gardener-extension-admission-cilium` Service topology-aware

---

hack/test-e2e-provider-local.sh

/kind bug
The prow cluster is using Gardenlinux 934 worker groups now, so `cgroupv2` support for docker-in-docker is required. 
This is available in `gardener@v1.69.1`.
Fixes #
```other operator
NONE
```

Use `gardener@v1.69.1` for e2e tests

---

charts/internal/cilium/charts/agent/values.yaml

/kind bug
Memory limits for cilium agent are increased to 10 Gi.
Fixes #
```other operator
Memory limits for cilium agent are increased to 10 Gi.
```

increase memory limit for cilium agent

---

charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/values.yaml
docs/usage-as-end-user.md

cilium can run Shoot clusters without kube-proxy. Additionally, according to my testing in local setup, even when kube-proxy is enabled, its [TopologyAwareHints feature](https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/) didn't work. I had to explicitly enable the corresponding feature on cilium side.
The change that implements the TopologyAwareHints (topology-aware traffic routing) in cilium is https://github.com/cilium/cilium/pull/17929. This PR enables the corresponding setting for Shoots using cilium.
In this way the topology-aware traffic routing feature in gardener (ref https://github.com/gardener/gardener/blob/master/docs/usage/topology_aware_routin …

Add support for TopologyAwareHints (topology-aware traffic routing)

---

Dockerfile
Makefile
cmd/gardener-extension-admission-cilium/app/app.go
cmd/gardener-extension-admission-cilium/main.go
cmd/gardener-extension-networking-cilium/app/app.go
cmd/gardener-extension-networking-cilium/main.go
vendor/k8s.io/component-base/version/verflag/verflag.go
vendor/modules.txt

Currently, it is hard to find the version of the `networking-cilium` images.
This PR improves this by inducing the version using ldflags.
Version can be printed by using the `--version` flag.
Also we log the version during the start of the component.
Also with this PR, docker images built by make docker-images are tagged and built with a version including the commit hash (exactly like the images built by the pipeline).
Fixes #
Similar to https://github.com/gardener/gardener-extension-networking-calico/pull/266
```other operator
NONE
```

Induce component version using ldflags

---

charts/internal/cilium/values.yaml

/kind bug
For large clusters the default value ("16384") of bpf-policy-map-max might be to small and result in errors like ```"Unable to update element for cilium_policy_01432 map with file descriptor 243: the map is full"``` thus the value of the bpf-policy-map-max field will be increased to "65536". This change will slightly increase the overall memory consumption of the cilium pods in the magnitude of a few megabytes.
Fixes #195
```other operator
bpf-policy-map-max value is increased to 65536.
```

increase bpf-policy-map-max to 65536

---

charts/gardener-extension-admission-cilium/charts/runtime/templates/deplyoment.yaml
charts/gardener-extension-admission-cilium/values.yaml

/area security
This PR adds the option to configure a projected volume for the validator which can be used as a kubeconfig. It is for example needed, if operators generate their kubeconfigs for the virtual garden cluster via the [TokenRequestor](https://github.com/gardener/gardener/blob/master/docs/concepts/resource-manager.md#tokeninvalidator-controller).
```feature operator
The `gardener-extension-admission-cilium` chart allows to optionally configure a projected volume based kubeconfig.
```

Add support for projected volume kubeconfig

---

charts/images.yaml

Update cilium to `v1.14.2`. For more information, see the [release notes](https://github.com/cilium/cilium/releases/tag/v1.14.2).
Fixes #
```other operator
Update cilium to `v1.14.2`.
```

update cilium to v1.14.2

---

charts/internal/cilium/charts/agent/templates/podsecuritypolicy.yaml
charts/internal/cilium/charts/agent/templates/servicemonitor.yaml
charts/internal/cilium/charts/hubble-relay/templates/podsecuritypolicy.yaml
charts/internal/cilium/charts/operator/templates/podsecuritypolicy.yaml
charts/internal/cilium/charts/operator/templates/servicemonitor.yaml

/kind bug
Some charts were missed to be adapted in https://github.com/gardener/gardener-extension-networking-cilium/pull/213/commits/cec9afeda59a8be5eb64974aaff7823a691127c3.
This PR adapts them.
Fixes #
```bugfix operator
An issue in the charts missing versions for some resources is now fixed.
```

Fix versioning in charts

---

pkg/controller/actuator_reconcile.go

/kind bug
Fix reconciliation of hibernated clusters.
In the past, the extension library utilized a lazy kubernetes client instantiation. However, this changed recently with gardener v1.80 and its controller-runtime update. Now, the kubernetes client creation will fail if the api-server is not available. In case a shoot cluster is hibernated, the api-server is not available. Hence, the reconciliation will run into a corresponding error. This was handled previously by discarding the error returned from the GET call. Now, we check first if the cluster is hibernated and only create the client if it is not.
None.
Previously, this caused …

Fix reconciliation of hibernated clusters.

---

pkg/controller/actuator_delete.go

Follow up - https://github.com/gardener/gardener-extension-networking-cilium/pull/213
This PR enhances the delete function so that it doesn't wait for MR to be gone in case of force-delete.
/invite @acumino  
Fixes #
```bugfix operator
The `actuator.Delete` doesn't wait for ManagedResources to get deleted in case of `ForceDelete`.
```

Don't wait for MR to get deleted in case of force-delete

---

charts/internal/cilium/charts/config/templates/configmap.yaml
pkg/charts/utils.go
pkg/controller/actuator_reconcile.go

`IPv4NativeRoutingCIDR = "0.0.0.0/0"` leads to an invalid iptables rule that never matches. In case of iptables-nft this leads to an error. The intention of choosing "0.0.0.0/0" was to have a CIDR that includes both pod and nodes range. However, cilium takes care not to masquerade traffic to node addresses. So it's save to choose the pod range for `IPv4NativeRoutingCIDR`. As a result, the iptables masquerade rules, that are added by the sidecars  are not needed anymore. `SnatOutOfCluster` and `SnatToUpstreamDNS` can be switched off as default.
default nat rules without overlay before the change:
```
Chain CILIUM_POST_nat (1 references)
pkts bytes target     prot opt in     out     source               destination
235 22730 MASQUERADE  all  --  *      !cilium_+  100.80.0.0/12 …
```

Fix error with iptables-nft.

---

imagevector/images.yaml

Update cilium to `v1.14.5`.
Fixes #
```other operator
Update cilium to `v1.14.5`.
```

update cilium to v1.14.5

---

charts/gardener-extension-admission-cilium/charts/runtime/templates/serviceaccount.yaml

/kind bug
With https://github.com/gardener/gardener-extension-networking-cilium/pull/234  the `apiVersion` field was removed from [`charts/gardener-extension-admission-cilium/charts/runtime/templates/serviceaccount.yaml`](https://github.com/timuthy/gardener-extension-networking-cilium/blob/1f83e49f815486c5130bcefaaaf2ea9ceb7d4092/charts/gardener-extension-admission-cilium/charts/runtime/templates/serviceaccount.yaml).
This causes the following error when using these charts to deploy the admission with the [local gardener setup with extensions](https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally_with_extensions.md):
```
[error validating data: apiVersion not set; if …
```

Add `apiVersion: v1` to gardener-extension-admission-cilium `ServiceAccount`

---

charts/internal/cilium/values.yaml

/kind bug
Fix casing of l7 proxy configuration to enable it by default.
Fixes #257.
The usage of this helm option
https://github.com/gardener/gardener-extension-networking-cilium/blob/313bf583be3b6b8ae9c0db4b013ffdc7e6672f5a/charts/internal/cilium/charts/config/templates/configmap.yaml#L313
was using `l7Proxy` while it was introduced with the cilium 1.9.4 update as `l7proxy` in the configuration:
https://github.com/gardener/gardener-extension-networking-cilium/blob/313bf583be3b6b8ae9c0db4b013ffdc7e6672f5a/charts/internal/cilium/values.yaml#L462
```other operator
Cilium configuration option `enable-l7-proxy` is now …
```

Fix casing of l7 proxy configuration to enable it by default

---

test/e2e/common_test.go

Run e2e test cluster without kube-proxy.
Fixes #
```other operator
```

run e2e test cluster without kube-proxy

---

test/e2e/network_test.go

/kind test
Fixes #
```other operator
```

Remove unneeded kubeconfig secret from e2e test.

---

charts/gardener-extension-admission-cilium/charts/runtime/templates/deplyoment.yaml
charts/gardener-extension-admission-cilium/values.yaml

/area robustness
This PR enhances the admission chart by the option to set a `priorityClassName`.
Part of https://github.com/gardener/gardener/issues/9936.
```other operator
A `priorityClassName` can now be set for the admission deployment via the `gardener-extension-admission-cilium` Helm chart.
```

[admission] Add `priorityClassName`

---

.ci/pipeline_definitions

/kind bug
The paths of the admission Helm charts in #376 are wrong. This PR fixes them.
Fixes #
/cc @ScheererJ 
```other operator
NONE
```

Fix path of admission Helm charts in pipeline definition

---

.gitignore
Makefile
hack/sast.sh
pkg/apis/config/loader/loader.go

/area security
/area compliance
This PR introduces `gosec` for Static Application Security Testing at Gardener and should replace other code scanners.
It uses the default ruleset of `gosec` from gardener/gardener as introduced in https://github.com/gardener/gardener/pull/9959.
Fixes #
Until https://github.com/gardener/gardener/pull/10642 is in a gardener/gardener release there is a small workaround necessary, which will be removed afterwards.
```other operator
`gosec` was introduced for Static Application Security Testing (SAST).
```

Introduce `gosec` for Static Application Security Testing (SAST)

---

pkg/charts/utils.go
pkg/controller/actuator_reconcile.go

/kind bug
Fix nil dereference in [IPv6 support](https://github.com/gardener/gardener-extension-networking-cilium/pull/421) in case no network config was specified.
In addition to that, the code is simplified and redundancy has been removed.
Fixes #
```other operator
```

Allow running without network config

---

charts/internal/cilium/values.yaml

Fixes #
```other operator
Disable masquerading of IPv6 pod traffic which leaves the cluster.
```

Disabable IPv6 masquerading.

---

test/templates/network-test.yaml.tpl

/kind test
This PR adds a tests that assures access to kube-apiserver through apiserver-proxy is possible during network test. 
Aims to check during e2e tests that changes to the cilium configuration don't break access to kube-apiserver like we saw here: https://github.com/gardener/gardener-extension-networking-cilium/pull/350#issuecomment-2273032839
```other operator
NONE
```

test(e2e): access kube-apiserver through apiserver-proxy

---

charts/internal/cilium/charts/config/templates/configmap.yaml

/kind TODO
Enable bpf-masquerading on direct routing if SNAT masquerades are not enabled.
For more information see the issue.
Fixes #349 
```other operator
Use BPF masquerading and therefore BPF host routing in Cilium when using direct routing.
```

fix: enable-bpf-masquerade when snat values are not enabled

---

charts/internal/cilium/charts/config/templates/configmap.yaml

According to https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/, health checking must be disabled, if not replacing kube-proxy. Respect this in the config map.
Details from doc:
kubeProxyReplacement=false: This option is used to disable any Kubernetes service handling by fully relying on kube-proxy instead, except for ClusterIP services accessed from pods (pre-v1.6 behavior), or for a hybrid setup. That is, kube-proxy is running in the Kubernetes cluster where Cilium partially replaces and optimizes kube-proxy functionality. The false option requires the user to manually specify which components for the eBPF kube-proxy replacement should be used. Similarly to true mode, the Cilium agent will bail out on start-up with an error message if the underlying kernel requirements …

disable health-check when not replacing kubeproxy

---

test/templates/network-test.yaml.tpl

This reverts commit 914ae763a582f6ab3cf9ea040b8ff772d0d9c261.
We will enable the test again, when we have a gardener release with the new apiserver-proxy image.
/kind test
Fixes #
```other operator
```

Revert "test: access kube-apiserver through apiserver-proxy"

---

test/templates/network-test.yaml.tpl

Merge after update to gardener release 1.113.
/kind test
Fixes #
```other test
test: access kube-apiserver through apiserver-proxy
```

Re-enable "test: access kube-apiserver through apiserver-proxy"

---

charts/internal/cilium/charts/config/templates/configmap.yaml
charts/internal/cilium/charts/envoy/templates/configmap.yaml
charts/internal/cilium/charts/envoy/templates/daemonset.yaml
charts/internal/cilium/charts/hubble-relay/templates/configmap.yaml
charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
charts/internal/cilium/charts/hubble-relay/templates/job.yaml
charts/internal/cilium/charts/operator/templates/clusterrole.yaml
charts/internal/cilium/charts/operator/templates/deployment.yaml
charts/internal/cilium/values.yaml
imagevector/images.yaml

Fixes #
```other operator
Update cilium to v1.17.1
```

Update cilium to v1.17.1

---

charts/internal/cilium/charts/config/templates/configmap.yaml

/kind bug
Fixes #
```other operator
Fix an issue where creating IPv6-only shoots fails.
```

Only enable bpf-masquerade for IPv4 and dual-stack.

---

Makefile
charts/internal/cilium/charts/agent/templates/daemonset.yaml
charts/internal/cilium/charts/envoy/templates/daemonset.yaml
charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
charts/internal/cilium/charts/hubble-relay/templates/network-policy.yaml
charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
charts/internal/cilium/charts/network-policy/templates/nodelocaldns.yaml
charts/internal/cilium/charts/operator/templates/deployment.yaml
test/e2e/common_test.go
test/e2e/network_connectivity_test.go
test/e2e/network_test.go
test/templates/network-connectivity-test.yaml.tpl

- Added labels and network policies to make sure cilium still works with a deny-all policy present in the kube-system namespace.
- Added network policy to support node-local-dns
- Added network policy to support hubble
```noteworthy operator
Cilium extension now supports a deny-all network policy within the kube-system namespace that [will come with kubernetes v1.33](https://github.com/gardener/gardener/pull/11502)
```

Cilium deny all netpol prepare

---

imagevector/images.yaml

bump glibc to v2.39 to fix issues found in v2.35
/kind bug
A couple of issues were found that got fixed in glibc >= v2.39
```noteworthy dependency
cilium-envoy got updated to v1.32.5
```

bump cilium-envoy to v1.32.5

---

pkg/controller/actuator_reconcile.go

Allow usage of extension in Autonomous Shoot Cluster scenario.
Autonomous shoot clusters do not have the equivalent of the gardener secret containing a kubeconfig for the control plane. As seed and shoot cluster are basically the same thing in this scenario there is no need for this secret. Therefore, extensions should work with what they have.
While it is possible to just use the seed client instead, in this case it is also possible to simply not retrieve the config maps at all because there is anyway a fallback logic in place. This way the code is not cluttered with autonomous shoot cluster specifics, but will continue to work nevertheless.
Part of …

[GEP-28] Allow usage of extension in Autonomous Shoot Cluster scenario.

---

charts/internal/cilium/charts/config/templates/configmap.yaml
hack/api-reference/cilium.md
pkg/apis/cilium/types_network.go
pkg/apis/cilium/v1alpha1/types_network.go
pkg/apis/cilium/v1alpha1/zz_generated.conversion.go
pkg/apis/cilium/v1alpha1/zz_generated.deepcopy.go
pkg/apis/cilium/zz_generated.deepcopy.go
pkg/charts/config.go
pkg/charts/utils.go
renovate.json5

/kind api-change
In one of our setups with metal-stack and Cilium the BPF masquerading needs to be disabled in order to work.
I simply added the fields to override the existing values in the values.yaml of the internal helm chart. Most other fields could already be set. Therefore I just expanded the current approach.
```other operator
Allows disabling IPv4, IPv6 and BPF masquerading in networking-cilium extension.
```

feat: allow disabling BPF masquerading

---

test/e2e/common_test.go

/kind flake
- I've observed many intermittent failures of the connectivity test that are caused by VPA evictions of kube-apiserver, vpn-shoot or vpn-seed-server mid-test
- This PR disables VPA and other autoscaling of kube-apiserver and vpn components in an effort to get more stability into the connectivity test.
```other developer
connectivity test stability has been improved and should be less flaky now
```

fix: disable vpa to stabilize con tests

---

example/20-network.yaml
hack/api-reference/config.json

/kind cleanup
Drop support for Shoots, Seeds and Gardens with Kubernetes version <= 1.28.
Part of https://github.com/gardener/gardener/issues/12409
N/A
```other operator
`networking-cilium` no longer supports Shoots with Кubernetes version <= 1.28.
```

Drop support for Shoots with Kubernetes version <= 1.28

---

charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
charts/internal/cilium/charts/hubble-relay/templates/job.yaml

/kind bug
Add labels for access to dns and api
Fixes #604
Should this be implemented in network-policy?
```
category: bugfix
fix hubble-generate-certs using labels 
```

allow hubble-generate-certs job access to api (via internal domain)

---

charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
charts/internal/cilium/charts/hubble-relay/templates/job.yaml

/kind bug
Include `networking.gardener.cloud/to-apiserver: allowed` label for hubble cert-gen jobs. `to-public-networks` is not enough for api servers that have private IP addresses.
```bugfix operator
Hubble relay cert generation now also works with private api server deployments
```

fix: include apiserver label for private clouds

---

pkg/controller/status.go

/kind bug
Check if IPFamily is enabled before adding to status. 
Fixes #
```other operator
Fixes an issue where network status is not correct during migration to dual-stack. 
```

Fix migration to dual-stack

---

charts/internal/cilium/charts/agent/templates/daemonset.yaml
imagevector/images.yaml

chore(deps): update cilium images to v1.17.7 (patch) (#621)
* chore(deps): update cilium images to v1.17.7
* Update cilium-envoy image
* Update liveness probe to not check for kubernetes connectivity
* Run `make generate`
Fixes #
```other operator
Update cilium to v1.17.7
```

Hotfix: Update cilium images to v1.17.7 (patch)

---

charts/internal/cilium-monitoring/templates/scrapeconfig-operator.yaml

/area monitoring
/kind bug
Fix casing for `ScrapeConfig` role.
Since [github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring@v0.76.0](https://github.com/prometheus-operator/prometheus-operator/releases/tag/pkg/apis/monitoring/v0.76.0) only camel case roles are valid in ScrapeConfigs of monitoring.coreos.com/v1alpha1 (https://github.com/prometheus-operator/prometheus-operator/commit/38900ce#diff-95caef4dacf48c47bf56afc00c513822feba29a5d2f6354b75c97a25a353d52fL75-R77).
See also https://github.com/gardener/gardener/issues/12401.
Part of https://github.com/gardener/gardener/issues/12401.
```bugfix …
```

Fix casing for `ScrapeConfig` role
